apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: syntaris-harmony
    newName: ghcr.io/lichtara/syntaris-harmony
    newTag: latest
