apiVersion: v1
kind: Service
metadata:
  name: syntaris-harmony
  labels:
    app.kubernetes.io/name: syntaris-harmony
    app.kubernetes.io/part-of: lichtara
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: syntaris-harmony
  ports:
    - name: http
      port: 80
      targetPort: http

