version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/v5"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"