apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/part-of: lichtara
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: alloy
  ports:
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc

