apiVersion: v1
kind: Namespace
metadata:
  name: lichtara
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-deployer
  namespace: lichtara
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ci-deployer-role
  namespace: lichtara
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["services", "configmaps"]
    verbs: ["*"]
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["servicemonitors", "podmonitors", "prometheusrules"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["otel-auth"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ci-deployer-binding
  namespace: lichtara
subjects:
  - kind: ServiceAccount
    name: ci-deployer
    namespace: lichtara
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ci-deployer-role
