name: CI Portal
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node
        uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci --workspace apps/app-web || true
      - run: npm run build --workspace apps/app-web || true
      - run: echo "lint/test placeholders"

