name: lumora-release

on:
  workflow_dispatch:
    inputs:
      region:
        description: GCP region
        required: false
        default: sa-east1
      service_name:
        description: Cloud Run service name
        required: false
        default: lumora

permissions:
  contents: read
  packages: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Auth GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Enable required APIs
        run: |
          gcloud services enable run.googleapis.com secretmanager.googleapis.com artifactregistry.googleapis.com
      - name: Configure Docker for gcr.io
        run: gcloud auth configure-docker --quiet
      - name: Pull GHCR image and retag to GCR
        env:
          GHCR_IMAGE: ghcr.io/${{ github.repository_owner }}/lumora:${{ github.sha }}
          GCR_IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/lumora:${{ github.sha }}
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker pull "$GHCR_IMAGE" || {
            echo "Image not found for SHA; building locally";
            docker build -t "$GHCR_IMAGE" .;
          }
          docker tag "$GHCR_IMAGE" "$GCR_IMAGE"
          docker push "$GCR_IMAGE"
          echo "GCR_IMAGE=$GCR_IMAGE" >> $GITHUB_ENV
      - name: (Optional) Sync OPENAI_API_KEY to Secret Manager
        if: ${{ secrets.GCP_SYNC_SECRETS == 'true' && secrets.OPENAI_API_KEY != '' }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          gcloud secrets create OPENAI_API_KEY --replication-policy=automatic || true
          echo -n "$OPENAI_API_KEY" | gcloud secrets versions add OPENAI_API_KEY --data-file=-
      - name: Deploy to Cloud Run
        env:
          REGION: ${{ inputs.region }}
          SERVICE_NAME: ${{ inputs.service_name }}
        run: |
          REGION=${REGION:-sa-east1}
          SERVICE_NAME=${SERVICE_NAME:-lumora}
          gcloud run deploy "$SERVICE_NAME" \
            --image "${{ env.GCR_IMAGE }}" \
            --platform managed \
            --region "$REGION" \
            --allow-unauthenticated \
            --set-secrets OPENAI_API_KEY=OPENAI_API_KEY:latest \
            --set-env-vars LUMORA_MODEL=${{ secrets.LUMORA_MODEL || 'gpt-4o-mini' }},LUMORA_TEMPERATURE=${{ secrets.LUMORA_TEMPERATURE || '0.2' }}

